/* Word banks for Say It Right.
 *
 * Levels follow English File Beginner / Elementary / Pre-Intermediate.
 * Each entry: syl = syllable split (must join to the spelling), stress = index
 * of the stressed syllable (0-based). Single-syllable words use stress 0.
 * British English stress throughout, as in English File.
 *
 * Teachers: edit freely. npm-free; validate with `node validate.js`.
 */

const WORDS = {
  beginner: [
    { w: 'book', syl: ['book'], stress: 0 },
    { w: 'pen', syl: ['pen'], stress: 0 },
    { w: 'house', syl: ['house'], stress: 0 },
    { w: 'phone', syl: ['phone'], stress: 0 },
    { w: 'chair', syl: ['chair'], stress: 0 },
    { w: 'bread', syl: ['bread'], stress: 0 },
    { w: 'table', syl: ['ta', 'ble'], stress: 0 },
    { w: 'window', syl: ['win', 'dow'], stress: 0 },
    { w: 'teacher', syl: ['tea', 'cher'], stress: 0 },
    { w: 'student', syl: ['stu', 'dent'], stress: 0 },
    { w: 'coffee', syl: ['co', 'ffee'], stress: 0 },
    { w: 'water', syl: ['wa', 'ter'], stress: 0 },
    { w: 'city', syl: ['ci', 'ty'], stress: 0 },
    { w: 'doctor', syl: ['doc', 'tor'], stress: 0 },
    { w: 'sister', syl: ['sis', 'ter'], stress: 0 },
    { w: 'brother', syl: ['bro', 'ther'], stress: 0 },
    { w: 'mother', syl: ['mo', 'ther'], stress: 0 },
    { w: 'father', syl: ['fa', 'ther'], stress: 0 },
    { w: 'seven', syl: ['se', 'ven'], stress: 0 },
    { w: 'Monday', syl: ['Mon', 'day'], stress: 0 },
    { w: 'April', syl: ['A', 'pril'], stress: 0 },
    { w: 'chicken', syl: ['chi', 'cken'], stress: 0 },
    { w: 'orange', syl: ['o', 'range'], stress: 0 },
    { w: 'pizza', syl: ['pi', 'zza'], stress: 0 },
    { w: 'China', syl: ['Chi', 'na'], stress: 0 },
    { w: 'Russia', syl: ['Ru', 'ssia'], stress: 0 },
    { w: 'hotel', syl: ['ho', 'tel'], stress: 1 },
    { w: 'guitar', syl: ['gui', 'tar'], stress: 1 },
    { w: 'police', syl: ['po', 'lice'], stress: 1 },
    { w: 'hello', syl: ['he', 'llo'], stress: 1 },
    { w: 'goodbye', syl: ['good', 'bye'], stress: 1 },
    { w: 'thirteen', syl: ['thir', 'teen'], stress: 1 },
    { w: 'eleven', syl: ['e', 'le', 'ven'], stress: 1 },
    { w: 'banana', syl: ['ba', 'na', 'na'], stress: 1 },
    { w: 'computer', syl: ['com', 'pu', 'ter'], stress: 1 },
    { w: 'family', syl: ['fa', 'mi', 'ly'], stress: 0 },
    { w: 'milk', syl: ['milk'], stress: 0 },
    { w: 'cheese', syl: ['cheese'], stress: 0 },
    { w: 'school', syl: ['school'], stress: 0 },
    { w: 'friend', syl: ['friend'], stress: 0 },
    { w: 'street', syl: ['street'], stress: 0 },
    { w: 'nurse', syl: ['nurse'], stress: 0 },
    { w: 'morning', syl: ['mor', 'ning'], stress: 0 },
    { w: 'evening', syl: ['eve', 'ning'], stress: 0 },
    { w: 'dinner', syl: ['di', 'nner'], stress: 0 },
    { w: 'children', syl: ['chil', 'dren'], stress: 0 },
    { w: 'daughter', syl: ['daugh', 'ter'], stress: 0 },
    { w: 'husband', syl: ['hus', 'band'], stress: 0 },
    { w: 'people', syl: ['peo', 'ple'], stress: 0 },
    { w: 'money', syl: ['mo', 'ney'], stress: 0 },
    { w: 'music', syl: ['mu', 'sic'], stress: 0 },
    { w: 'apple', syl: ['a', 'pple'], stress: 0 },
    { w: 'butter', syl: ['bu', 'tter'], stress: 0 },
    { w: 'sugar', syl: ['su', 'gar'], stress: 0 },
    { w: 'waiter', syl: ['wai', 'ter'], stress: 0 },
    { w: 'happy', syl: ['ha', 'ppy'], stress: 0 },
    { w: 'hungry', syl: ['hun', 'gry'], stress: 0 },
    { w: 'yellow', syl: ['ye', 'llow'], stress: 0 },
    { w: 'purple', syl: ['pur', 'ple'], stress: 0 },
    { w: 'sorry', syl: ['so', 'rry'], stress: 0 },
    { w: 'thirty', syl: ['thir', 'ty'], stress: 0 },
    { w: 'fifty', syl: ['fif', 'ty'], stress: 0 },
    { w: 'Sunday', syl: ['Sun', 'day'], stress: 0 },
    { w: 'Friday', syl: ['Fri', 'day'], stress: 0 },
    { w: 'August', syl: ['Au', 'gust'], stress: 0 },
    { w: 'Turkey', syl: ['Tur', 'key'], stress: 0 },
    { w: 'fourteen', syl: ['four', 'teen'], stress: 1 },
    { w: 'fifteen', syl: ['fif', 'teen'], stress: 1 },
    { w: 'eighteen', syl: ['eigh', 'teen'], stress: 1 },
    { w: 'Brazil', syl: ['Bra', 'zil'], stress: 1 },
    { w: 'Japan', syl: ['Ja', 'pan'], stress: 1 },
    { w: 'today', syl: ['to', 'day'], stress: 1 },
    { w: 'tonight', syl: ['to', 'night'], stress: 1 },
    { w: 'again', syl: ['a', 'gain'], stress: 1 },
    { w: 'because', syl: ['be', 'cause'], stress: 1 },
    { w: 'Italy', syl: ['I', 'ta', 'ly'], stress: 0 },
    { w: 'Germany', syl: ['Ger', 'ma', 'ny'], stress: 0 },
    { w: 'manager', syl: ['ma', 'na', 'ger'], stress: 0 },
    { w: 'October', syl: ['Oc', 'to', 'ber'], stress: 1 },
    { w: 'November', syl: ['No', 'vem', 'ber'], stress: 1 },
    { w: 'December', syl: ['De', 'cem', 'ber'], stress: 1 },
    { w: 'September', syl: ['Sep', 'tem', 'ber'], stress: 1 },
    { w: 'potato', syl: ['po', 'ta', 'to'], stress: 1 },
    { w: 'tomato', syl: ['to', 'ma', 'to'], stress: 1 },
    { w: 'Korea', syl: ['Ko', 're', 'a'], stress: 1 },
    { w: 'Kazakhstan', syl: ['Ka', 'zakh', 'stan'], stress: 2 },
  ],

  elementary: [
    { w: 'breakfast', syl: ['break', 'fast'], stress: 0 },
    { w: 'favourite', syl: ['fa', 'vou', 'rite'], stress: 0 },
    { w: 'beautiful', syl: ['beau', 'ti', 'ful'], stress: 0 },
    { w: 'difficult', syl: ['di', 'ffi', 'cult'], stress: 0 },
    { w: 'restaurant', syl: ['res', 'tau', 'rant'], stress: 0 },
    { w: 'holiday', syl: ['ho', 'li', 'day'], stress: 0 },
    { w: 'Saturday', syl: ['Sa', 'tur', 'day'], stress: 0 },
    { w: 'hospital', syl: ['hos', 'pi', 'tal'], stress: 0 },
    { w: 'medicine', syl: ['me', 'di', 'cine'], stress: 0 },
    { w: 'vegetable', syl: ['ve', 'ge', 'table'], stress: 0 },
    { w: 'exercise', syl: ['ex', 'er', 'cise'], stress: 0 },
    { w: 'newspaper', syl: ['news', 'pa', 'per'], stress: 0 },
    { w: 'grandmother', syl: ['grand', 'mo', 'ther'], stress: 0 },
    { w: 'comfortable', syl: ['com', 'for', 'table'], stress: 0 },
    { w: 'interesting', syl: ['in', 'te', 'res', 'ting'], stress: 0 },
    { w: 'expensive', syl: ['ex', 'pen', 'sive'], stress: 1 },
    { w: 'important', syl: ['im', 'por', 'tant'], stress: 1 },
    { w: 'tomorrow', syl: ['to', 'mo', 'rrow'], stress: 1 },
    { w: 'together', syl: ['to', 'ge', 'ther'], stress: 1 },
    { w: 'remember', syl: ['re', 'mem', 'ber'], stress: 1 },
    { w: 'arrive', syl: ['a', 'rrive'], stress: 1 },
    { w: 'decide', syl: ['de', 'cide'], stress: 1 },
    { w: 'invite', syl: ['in', 'vite'], stress: 1 },
    { w: 'prefer', syl: ['pre', 'fer'], stress: 1 },
    { w: 'relax', syl: ['re', 'lax'], stress: 1 },
    { w: 'begin', syl: ['be', 'gin'], stress: 1 },
    { w: 'afternoon', syl: ['af', 'ter', 'noon'], stress: 2 },
    { w: 'understand', syl: ['un', 'der', 'stand'], stress: 2 },
    { w: 'engineer', syl: ['en', 'gi', 'neer'], stress: 2 },
    { w: 'Japanese', syl: ['Ja', 'pa', 'nese'], stress: 2 },
    { w: 'supermarket', syl: ['su', 'per', 'mar', 'ket'], stress: 0 },
    { w: 'dictionary', syl: ['dic', 'tio', 'na', 'ry'], stress: 0 },
    { w: 'weather', syl: ['wea', 'ther'], stress: 0 },
    { w: 'cloudy', syl: ['clou', 'dy'], stress: 0 },
    { w: 'windy', syl: ['win', 'dy'], stress: 0 },
    { w: 'sunny', syl: ['su', 'nny'], stress: 0 },
    { w: 'friendly', syl: ['friend', 'ly'], stress: 0 },
    { w: 'crowded', syl: ['crow', 'ded'], stress: 0 },
    { w: 'modern', syl: ['mo', 'dern'], stress: 0 },
    { w: 'famous', syl: ['fa', 'mous'], stress: 0 },
    { w: 'boring', syl: ['bo', 'ring'], stress: 0 },
    { w: 'airport', syl: ['air', 'port'], stress: 0 },
    { w: 'passport', syl: ['pass', 'port'], stress: 0 },
    { w: 'sandwich', syl: ['sand', 'wich'], stress: 0 },
    { w: 'village', syl: ['vi', 'llage'], stress: 0 },
    { w: 'country', syl: ['coun', 'try'], stress: 0 },
    { w: 'mountain', syl: ['moun', 'tain'], stress: 0 },
    { w: 'island', syl: ['i', 'sland'], stress: 0 },
    { w: 'travel', syl: ['tra', 'vel'], stress: 0 },
    { w: 'visit', syl: ['vi', 'sit'], stress: 0 },
    { w: 'borrow', syl: ['bo', 'rrow'], stress: 0 },
    { w: 'promise', syl: ['pro', 'mise'], stress: 0 },
    { w: 'practise', syl: ['prac', 'tise'], stress: 0 },
    { w: 'machine', syl: ['ma', 'chine'], stress: 1 },
    { w: 'explain', syl: ['ex', 'plain'], stress: 1 },
    { w: 'describe', syl: ['de', 'scribe'], stress: 1 },
    { w: 'surprised', syl: ['sur', 'prised'], stress: 1 },
    { w: 'weekend', syl: ['week', 'end'], stress: 1 },
    { w: 'delicious', syl: ['de', 'li', 'cious'], stress: 1 },
    { w: 'exciting', syl: ['ex', 'ci', 'ting'], stress: 1 },
    { w: 'excited', syl: ['ex', 'ci', 'ted'], stress: 1 },
    { w: 'amazing', syl: ['a', 'ma', 'zing'], stress: 1 },
    { w: 'annoying', syl: ['a', 'nnoy', 'ing'], stress: 1 },
    { w: 'umbrella', syl: ['um', 'bre', 'lla'], stress: 1 },
    { w: 'apartment', syl: ['a', 'part', 'ment'], stress: 1 },
    { w: 'museum', syl: ['mu', 'se', 'um'], stress: 1 },
    { w: 'continue', syl: ['con', 'ti', 'nue'], stress: 1 },
    { w: 'discover', syl: ['dis', 'co', 'ver'], stress: 1 },
    { w: 'imagine', syl: ['i', 'ma', 'gine'], stress: 1 },
    { w: 'dangerous', syl: ['dan', 'ge', 'rous'], stress: 0 },
    { w: 'wonderful', syl: ['won', 'der', 'ful'], stress: 0 },
    { w: 'terrible', syl: ['te', 'rri', 'ble'], stress: 0 },
    { w: 'horrible', syl: ['ho', 'rri', 'ble'], stress: 0 },
    { w: 'bicycle', syl: ['bi', 'cy', 'cle'], stress: 0 },
    { w: 'chocolate', syl: ['cho', 'co', 'late'], stress: 0 },
    { w: 'furniture', syl: ['fur', 'ni', 'ture'], stress: 0 },
    { w: 'library', syl: ['li', 'bra', 'ry'], stress: 0 },
    { w: 'calendar', syl: ['ca', 'len', 'dar'], stress: 0 },
    { w: 'cinema', syl: ['ci', 'ne', 'ma'], stress: 0 },
    { w: 'organise', syl: ['or', 'ga', 'nise'], stress: 0 },
    { w: 'volunteer', syl: ['vo', 'lun', 'teer'], stress: 2 },
    { w: 'souvenir', syl: ['sou', 've', 'nir'], stress: 2 },
    { w: 'invitation', syl: ['in', 'vi', 'ta', 'tion'], stress: 2 },
    { w: 'celebration', syl: ['ce', 'le', 'bra', 'tion'], stress: 2 },
    { w: 'conversation', syl: ['con', 'ver', 'sa', 'tion'], stress: 2 },
  ],

  preint: [
    { w: 'photograph', syl: ['pho', 'to', 'graph'], stress: 0 },
    { w: 'photographer', syl: ['pho', 'to', 'gra', 'pher'], stress: 1 },
    { w: 'photographic', syl: ['pho', 'to', 'gra', 'phic'], stress: 2 },
    { w: 'economy', syl: ['e', 'co', 'no', 'my'], stress: 1 },
    { w: 'economic', syl: ['e', 'co', 'no', 'mic'], stress: 2 },
    { w: 'politics', syl: ['po', 'li', 'tics'], stress: 0 },
    { w: 'political', syl: ['po', 'li', 'ti', 'cal'], stress: 1 },
    { w: 'technology', syl: ['tech', 'no', 'lo', 'gy'], stress: 1 },
    { w: 'technological', syl: ['tech', 'no', 'lo', 'gi', 'cal'], stress: 2 },
    { w: 'information', syl: ['in', 'for', 'ma', 'tion'], stress: 2 },
    { w: 'education', syl: ['e', 'du', 'ca', 'tion'], stress: 2 },
    { w: 'competition', syl: ['com', 'pe', 'ti', 'tion'], stress: 2 },
    { w: 'communication', syl: ['co', 'mmu', 'ni', 'ca', 'tion'], stress: 3 },
    { w: 'pronunciation', syl: ['pro', 'nun', 'ci', 'a', 'tion'], stress: 3 },
    { w: 'decision', syl: ['de', 'ci', 'sion'], stress: 1 },
    { w: 'television', syl: ['te', 'le', 'vi', 'sion'], stress: 0 },
    { w: 'opportunity', syl: ['o', 'ppor', 'tu', 'ni', 'ty'], stress: 2 },
    { w: 'necessary', syl: ['ne', 'ce', 'ssa', 'ry'], stress: 0 },
    { w: 'environment', syl: ['en', 'vi', 'ron', 'ment'], stress: 1 },
    { w: 'advertisement', syl: ['ad', 'ver', 'tise', 'ment'], stress: 1 },
    { w: 'interview', syl: ['in', 'ter', 'view'], stress: 0 },
    { w: 'experience', syl: ['ex', 'pe', 'ri', 'ence'], stress: 1 },
    { w: 'independent', syl: ['in', 'de', 'pen', 'dent'], stress: 2 },
    { w: 'responsible', syl: ['re', 'spon', 'si', 'ble'], stress: 1 },
    { w: 'successful', syl: ['suc', 'cess', 'ful'], stress: 1 },
    { w: 'unemployed', syl: ['un', 'em', 'ployed'], stress: 2 },
    { w: 'particularly', syl: ['par', 'ti', 'cu', 'lar', 'ly'], stress: 1 },
    { w: 'immediately', syl: ['i', 'mme', 'dia', 'te', 'ly'], stress: 1 },
    { w: 'certificate', syl: ['cer', 'ti', 'fi', 'cate'], stress: 1 },
    { w: 'comfortable', syl: ['com', 'for', 'table'], stress: 0 },
    { w: 'vocabulary', syl: ['vo', 'ca', 'bu', 'la', 'ry'], stress: 1 },
    { w: 'temperature', syl: ['tem', 'pe', 'ra', 'ture'], stress: 0 },
    { w: 'national', syl: ['na', 'tio', 'nal'], stress: 0 },
    { w: 'nationality', syl: ['na', 'tio', 'na', 'li', 'ty'], stress: 2 },
    { w: 'personal', syl: ['per', 'so', 'nal'], stress: 0 },
    { w: 'personality', syl: ['per', 'so', 'na', 'li', 'ty'], stress: 2 },
    { w: 'medical', syl: ['me', 'di', 'cal'], stress: 0 },
    { w: 'scientist', syl: ['sci', 'en', 'tist'], stress: 0 },
    { w: 'scientific', syl: ['sci', 'en', 'ti', 'fic'], stress: 2 },
    { w: 'possible', syl: ['po', 'ssi', 'ble'], stress: 0 },
    { w: 'possibility', syl: ['po', 'ssi', 'bi', 'li', 'ty'], stress: 2 },
    { w: 'advertise', syl: ['ad', 'ver', 'tise'], stress: 0 },
    { w: 'photography', syl: ['pho', 'to', 'gra', 'phy'], stress: 1 },
    { w: 'government', syl: ['go', 'vern', 'ment'], stress: 0 },
    { w: 'management', syl: ['ma', 'nage', 'ment'], stress: 0 },
    { w: 'championship', syl: ['cham', 'pion', 'ship'], stress: 0 },
    { w: 'atmosphere', syl: ['at', 'mos', 'phere'], stress: 0 },
    { w: 'agriculture', syl: ['a', 'gri', 'cul', 'ture'], stress: 0 },
    { w: 'architecture', syl: ['ar', 'chi', 'tec', 'ture'], stress: 0 },
    { w: 'definitely', syl: ['de', 'fi', 'nite', 'ly'], stress: 0 },
    { w: 'probably', syl: ['pro', 'ba', 'bly'], stress: 0 },
    { w: 'actually', syl: ['ac', 'tu', 'a', 'lly'], stress: 0 },
    { w: 'suddenly', syl: ['su', 'dden', 'ly'], stress: 0 },
    { w: 'carefully', syl: ['care', 'fu', 'lly'], stress: 0 },
    { w: 'equipment', syl: ['e', 'quip', 'ment'], stress: 1 },
    { w: 'employment', syl: ['em', 'ploy', 'ment'], stress: 1 },
    { w: 'agreement', syl: ['a', 'gree', 'ment'], stress: 1 },
    { w: 'experiment', syl: ['ex', 'pe', 'ri', 'ment'], stress: 1 },
    { w: 'development', syl: ['de', 've', 'lop', 'ment'], stress: 1 },
    { w: 'relationship', syl: ['re', 'la', 'tion', 'ship'], stress: 1 },
    { w: 'traditional', syl: ['tra', 'di', 'tio', 'nal'], stress: 1 },
    { w: 'professional', syl: ['pro', 'fe', 'ssio', 'nal'], stress: 1 },
    { w: 'available', syl: ['a', 'vai', 'la', 'ble'], stress: 1 },
    { w: 'incredible', syl: ['in', 'cre', 'di', 'ble'], stress: 1 },
    { w: 'impossible', syl: ['im', 'po', 'ssi', 'ble'], stress: 1 },
    { w: 'ridiculous', syl: ['ri', 'di', 'cu', 'lous'], stress: 1 },
    { w: 'completely', syl: ['com', 'plete', 'ly'], stress: 1 },
    { w: 'especially', syl: ['e', 'spe', 'cia', 'lly'], stress: 1 },
    { w: 'unfortunately', syl: ['un', 'for', 'tu', 'nate', 'ly'], stress: 1 },
    { w: 'uncomfortable', syl: ['un', 'com', 'for', 'table'], stress: 1 },
    { w: 'approximately', syl: ['a', 'ppro', 'xi', 'mate', 'ly'], stress: 1 },
    { w: 'generation', syl: ['ge', 'ne', 'ra', 'tion'], stress: 2 },
    { w: 'entertainment', syl: ['en', 'ter', 'tain', 'ment'], stress: 2 },
    { w: 'disappointed', syl: ['di', 'sa', 'ppoin', 'ted'], stress: 2 },
    { w: 'engineering', syl: ['en', 'gi', 'nee', 'ring'], stress: 2 },
    { w: 'university', syl: ['u', 'ni', 'ver', 'si', 'ty'], stress: 2 },
    { w: 'electricity', syl: ['e', 'lec', 'tri', 'ci', 'ty'], stress: 2 },
    { w: 'international', syl: ['in', 'ter', 'na', 'tio', 'nal'], stress: 2 },
    { w: 'environmental', syl: ['en', 'vi', 'ron', 'men', 'tal'], stress: 2 },
    { w: 'accommodation', syl: ['a', 'cco', 'mmo', 'da', 'tion'], stress: 3 },
    { w: 'qualification', syl: ['qua', 'li', 'fi', 'ca', 'tion'], stress: 3 },
    { w: 'organisation', syl: ['or', 'ga', 'ni', 'sa', 'tion'], stress: 3 },
    { w: 'imagination', syl: ['i', 'ma', 'gi', 'na', 'tion'], stress: 3 },
    { w: 'recommendation', syl: ['re', 'co', 'mmen', 'da', 'tion'], stress: 3 },
    { w: 'responsibility', syl: ['re', 'spon', 'si', 'bi', 'li', 'ty'], stress: 3 },
  ],
};

/* Sound Bank pairs, in the style of English File's sound pictures.
 * Each pair: two words that differ by one sound, with the symbol and the
 * keyword English File uses for that sound.
 */
const PAIRS = {
  beginner: [
    { a: 'ship', b: 'sheep', soundA: ['/ɪ/', 'fish'], soundB: ['/iː/', 'tree'] },
    { a: 'live', b: 'leave', soundA: ['/ɪ/', 'fish'], soundB: ['/iː/', 'tree'] },
    { a: 'bad', b: 'bed', soundA: ['/æ/', 'cat'], soundB: ['/e/', 'egg'] },
    { a: 'man', b: 'men', soundA: ['/æ/', 'cat'], soundB: ['/e/', 'egg'] },
    { a: 'cat', b: 'cut', soundA: ['/æ/', 'cat'], soundB: ['/ʌ/', 'up'] },
    { a: 'hat', b: 'hot', soundA: ['/æ/', 'cat'], soundB: ['/ɒ/', 'clock'] },
    { a: 'full', b: 'fool', soundA: ['/ʊ/', 'bull'], soundB: ['/uː/', 'boot'] },
    { a: 'this', b: 'these', soundA: ['/ɪ/', 'fish'], soundB: ['/iː/', 'tree'] },
  ],
  elementary: [
    { a: 'think', b: 'sink', soundA: ['/θ/', 'thumb'], soundB: ['/s/', 'snake'] },
    { a: 'van', b: 'ban', soundA: ['/v/', 'vase'], soundB: ['/b/', 'bag'] },
    { a: 'work', b: 'walk', soundA: ['/ɜː/', 'bird'], soundB: ['/ɔː/', 'horse'] },
    { a: 'chair', b: 'share', soundA: ['/tʃ/', 'chess'], soundB: ['/ʃ/', 'shower'] },
    { a: 'light', b: 'right', soundA: ['/l/', 'leg'], soundB: ['/r/', 'robot'] },
    { a: 'cheap', b: 'jeep', soundA: ['/tʃ/', 'chess'], soundB: ['/dʒ/', 'jazz'] },
    { a: 'sing', b: 'thing', soundA: ['/s/', 'snake'], soundB: ['/θ/', 'thumb'] },
    { a: 'boat', b: 'bought', soundA: ['/əʊ/', 'phone'], soundB: ['/ɔː/', 'horse'] },
  ],
  preint: [
    { a: 'they', b: 'day', soundA: ['/ð/', 'mother'], soundB: ['/d/', 'dog'] },
    { a: 'hear', b: 'hair', soundA: ['/ɪə/', 'ear'], soundB: ['/eə/', 'chair'] },
    { a: 'thought', b: 'taught', soundA: ['/θ/', 'thumb'], soundB: ['/t/', 'tie'] },
    { a: 'pleasure', b: 'pressure', soundA: ['/ʒ/', 'television'], soundB: ['/ʃ/', 'shower'] },
    { a: 'won', b: 'want', soundA: ['/ʌ/', 'up'], soundB: ['/ɒ/', 'clock'] },
    { a: 'bird', b: 'beard', soundA: ['/ɜː/', 'bird'], soundB: ['/ɪə/', 'ear'] },
    { a: 'advice', b: 'advise', soundA: ['/s/', 'snake'], soundB: ['/z/', 'zebra'] },
    { a: 'yet', b: 'jet', soundA: ['/j/', 'yacht'], soundB: ['/dʒ/', 'jazz'] },
  ],
};

const LEVELS = [
  { id: 'beginner', name: 'Beginner' },
  { id: 'elementary', name: 'Elementary' },
  { id: 'preint', name: 'Pre-Intermediate' },
];

if (typeof module !== 'undefined') module.exports = { WORDS, PAIRS, LEVELS };
